[package]
name = "cncli"
version = "5.0.3"
authors = ["Andrew Westberg <andrewwestberg@gmail.com>"]
edition = "2018"
build = "build.rs"
links = "libsodium"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.8.0"
bigdecimal = "0.2.0"
num-bigint = "0.3.1"
blake2b_simd = "0.5.11"
byteorder = "1.3.4"
#pallas-miniprotocols = { git = "https://github.com/AndrewWestberg/pallas", rev="e41759c90fc32cfb478780126c8cd7fb7e831843" }
#pallas-multiplexer = { git = "https://github.com/AndrewWestberg/pallas", rev="e41759c90fc32cfb478780126c8cd7fb7e831843" }
#pallas-traverse = { git = "https://github.com/AndrewWestberg/pallas", rev="e41759c90fc32cfb478780126c8cd7fb7e831843" }
pallas-miniprotocols = "0.12.0-alpha.0"
pallas-multiplexer = "0.12.0-alpha.0"
pallas-traverse = "0.12.0-alpha.0"
chrono = "0.4.19"
chrono-tz = "0.5.3"
futures = "0.3.8"
hex = "0.4.2"
libc = "0.2.80"
net2 = "0.2.35"
regex = "1.4.2"
reqwest = { version = "0.11.0", features = ["blocking"] }
rug = { version = "1.11.0", default-features = false, features = ["integer", "rational", "float", "serde"] }
rusqlite = { version = "0.24.1", features = ["bundled"] }
serde = { version = "1.0.117", features = ["derive"] }
serde-aux = "2.1.1"
serde_cbor = "0.11.1"
serde_json = "1.0.62"
structopt = "0.3.20"
rand = "0.8.4"
rayon = "1.5.0"
itertools = "0.10.0"

# logging
log = "0.4.11"
env_logger = "0.8.1"
pretty_env_logger = "0.4.0"

# fix cross-compile
gmp-mpfr-sys = { version="1.4", features=["force-cross"] }

[build-dependencies]
autotools = "0.2"
pkg-config = "0.3.16"

[features]
libsodium-sys = []
